input.onButtonPressed(Button.A, function () {
    music.playTone(294, music.beat(BeatFraction.Half))
    music.playTone(294, music.beat(BeatFraction.Half))
    music.playTone(330, music.beat(BeatFraction.Whole))
    music.playTone(294, music.beat(BeatFraction.Whole))
    music.playTone(392, music.beat(BeatFraction.Whole))
    music.playTone(370, music.beat(BeatFraction.Double))
    music.playTone(294, music.beat(BeatFraction.Half))
    music.playTone(294, music.beat(BeatFraction.Half))
    music.playTone(330, music.beat(BeatFraction.Whole))
    music.playTone(294, music.beat(BeatFraction.Whole))
    music.playTone(440, music.beat(BeatFraction.Whole))
    music.playTone(392, music.beat(BeatFraction.Whole))
    music.playTone(294, music.beat(BeatFraction.Half))
    music.playTone(587, music.beat(BeatFraction.Whole))
    music.playTone(494, music.beat(BeatFraction.Whole))
    music.playTone(392, music.beat(BeatFraction.Whole))
    music.playTone(370, music.beat(BeatFraction.Whole))
    music.playTone(523, music.beat(BeatFraction.Half))
    music.playTone(523, music.beat(BeatFraction.Half))
    music.playTone(494, music.beat(BeatFraction.Whole))
    music.playTone(392, music.beat(BeatFraction.Whole))
    music.playTone(440, music.beat(BeatFraction.Whole))
    music.playTone(392, music.beat(BeatFraction.Whole))
})
input.onButtonPressed(Button.B, function () {
    music.playTone(523, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(523, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(784, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(784, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(880, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(880, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(784, music.beat(BeatFraction.Double))
    basic.pause(100)
    music.playTone(698, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(698, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(659, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(659, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(587, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(587, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(523, music.beat(BeatFraction.Double))
    basic.pause(100)
    music.playTone(784, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(784, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(698, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(698, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(659, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(659, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(587, music.beat(BeatFraction.Double))
    basic.pause(100)
    music.playTone(784, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(784, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(698, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(698, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(659, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(659, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(587, music.beat(BeatFraction.Double))
    basic.pause(100)
    music.playTone(523, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(523, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(784, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(784, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(880, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(880, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(784, music.beat(BeatFraction.Double))
    basic.pause(100)
    music.playTone(698, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(698, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(659, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(659, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(587, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(587, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(523, music.beat(BeatFraction.Double))
    music.rest(music.beat(BeatFraction.Breve))
    music.rest(music.beat(BeatFraction.Breve))
})
basic.forever(function () {
	
})
