def on_button_pressed_a():
    music.play_tone(294, music.beat(BeatFraction.QUARTER))
    music.play_tone(330, music.beat(BeatFraction.QUARTER))
    music.play_tone(349, music.beat(BeatFraction.QUARTER))
    music.play_tone(392, music.beat(BeatFraction.QUARTER))
    music.play_tone(880, music.beat(BeatFraction.WHOLE))
    music.play_tone(262, music.beat(BeatFraction.SIXTEENTH))
    music.play_tone(880, music.beat(BeatFraction.HALF))
    music.play_tone(784, music.beat(BeatFraction.DOUBLE))
    music.play_tone(294, music.beat(BeatFraction.QUARTER))
    music.play_tone(330, music.beat(BeatFraction.QUARTER))
    music.play_tone(349, music.beat(BeatFraction.QUARTER))
    music.play_tone(784, music.beat(BeatFraction.HALF))
    basic.pause(200)
    music.play_tone(784, music.beat(BeatFraction.HALF))
    music.play_tone(698, music.beat(BeatFraction.WHOLE))
    music.play_tone(659, music.beat(BeatFraction.QUARTER))
    music.play_tone(523, music.beat(BeatFraction.WHOLE))
    basic.pause(100)
    music.play_tone(494, music.beat(BeatFraction.QUARTER))
    music.play_tone(523, music.beat(BeatFraction.QUARTER))
    music.play_tone(587, music.beat(BeatFraction.HALF))
    music.play_tone(659, music.beat(BeatFraction.WHOLE))
    music.play_tone(698, music.beat(BeatFraction.HALF))
    music.play_tone(587, music.beat(BeatFraction.WHOLE))
    music.play_tone(659, music.beat(BeatFraction.WHOLE))
    music.play_tone(622, music.beat(BeatFraction.EIGHTH))
input.on_button_pressed(Button.A, on_button_pressed_a)

def on_forever():
    pass
basic.forever(on_forever)
